//type value: CONFIG 0,NORMAL 1,SKILL 2,BORNBUFF 3,BUFF 4,BULLET 5
{
    "LvBu":[{
		"file":"LvBu_Q",
		"skillID":0,
        "name":"LvBuQSkill",
		"cname":"十方俱灭",
        "recipes":[{
			"type":2,//skill
            "template":"RunSkillTemplate",
            "name":"LvBuQSkill",
			"cname":"十方俱灭"
        },
		{
			"type":4,//buff
			"template":"BuffTemplate",
            "name":"LvBuQBuff_speed",
			"cname":"十方俱灭（攻速）"
		},
		{
			"type":4,//buff
			"template":"BuffTemplate",
            "name":"LvBuQBuff_passive",
			"cname":"十方俱灭（附伤）"
		}
		]
    },
	{
		"file":"LvBu_W",
		"skillID":1,
        "name":"LvBuWSkill",
		"cname":"横扫千军",
        "recipes":[{
			"type":2,//skill
            "template":"SkillTemplate",
            "name":"LvBuWSkill",
			"cname":"横扫千军"
        },
		{
			"type":4,//buff
			"template":"BuffTemplate",
            "name":"LvBuWBuff_shield",
			"cname":"横扫千军（护盾）"
		}
		]
    },
	{
		"file":"LvBu_E",
		"skillID":2,
        "name":"LvBuESkill",
		"cname":"一骑当千",
        "recipes":[{
			"type":2,//skill
            "template":"SkillTemplate",
            "name":"LvBuESkill",
			"cname":"一骑当千"
        },
		{
			"type":4,//buff
			"template":"BuffTemplate",
            "name":"LvBuEBuff_passive",
			"cname":"一骑当千"
		},
		{
			"type":4,//buff
			"template":"BuffTemplate",
            "name":"LvBuEBuff_speed",
			"cname":"一骑当千（攻速下降）"
		}
		]
	},
	{
		"file":"LvBu_R",
		"skillID":3,
        "name":"LvBuRSkill",
		"cname":"魔神无双",
        "recipes":[{
			"type":2,//skill
            "template":"SkillTemplate",
            "name":"LvBuRSkill",
			"cname":"魔神无双"
        },
		{
			"type":4,//buff
			"template":"BuffTemplate",
            "name":"LvBuRBuff_stun",
			"cname":"魔神无双"
		}
		]
	},
	{
		"file":"LvBu_N",
		"skillID":-1,
        "name":"LvBuNSkill",
		"cname":"",
        "recipes":[{
			"type": 2,//skill
            "template":"NormalTemplate",
            "name":"LvBuNSkill",
			"cname":""
        }
		]
	},
	{
		"file":"LvBu_B",
		"skillID":98,
        "name":"LvBuBornBuff",
		"cname":"方天画戟",
        "recipes":[{
			"type": 3,//born buff
            "template":"BuffTemplate",
            "name":"LvBuBornBuff",
			"cname":"方天画戟"
        },
		{
			"type": 4,// buff
            "template":"BuffTemplate",
            "name":"LvBuBornBuff_armor",
			"cname":"方天画戟（降低护甲）"
        }
		]
	},
	{
		"file":"LvBu_config",
		//"skillID":,
        "name":"LvBu_config",
		"cname":"",
        "recipes":[{
			"type": 0,//config
            "template":"ConfigTemplate",
            "name":"LvBu_config",
			"cname":""
        }
		]
	}]
}